version: 2
registries:
  private-submodules:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.NEXUS_CICD_BOT_TOKEN }}
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Ho_Chi_Minh"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "automerge"
    registries:
      - private-submodules
